sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: https://oss-cn-guangzhou.aliyuncs.com
    bucket-name: noir-oss-bucket
    access-key-id: LTAI5tGdgPJ5qjPFhzniKyMm
    access-key-secret: lSNVsovDHIkrOpSBdPAUNBLrYWOyxj
  data:
    redis:
      host: localhost
      port: 6379
      # 非必须，默认0号数据库
      database: 0

